{{- if .Values.reload.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rm-frontend.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rm-frontend.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rm-frontend.fullname" . }}
{{- end }}